# Generated by Django 3.0.8 on 2020-08-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='type',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boot',
            name='colour',
            field=models.CharField(max_length=254),
        ),
    ]
