# Generated by Django 3.0.8 on 2020-08-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0002_auto_20200828_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boot',
            old_name='type',
            new_name='style',
        ),
    ]
