# Generated by Django 3.0.8 on 2020-08-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0003_auto_20200828_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
