# Generated by Django 3.0.8 on 2020-09-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0004_boot_has_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('comment', models.CharField(max_length=254)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('boot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boots.Boot')),
            ],
        ),
    ]
