# Generated by Django 3.0.8 on 2020-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='boot',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='boot',
            name='review',
            field=models.ManyToManyField(to='boots.Review'),
        ),
    ]
