# Generated by Django 3.0.8 on 2020-09-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0006_auto_20200911_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.RemoveField(
            model_name='boot',
            name='review',
        ),
        migrations.AddField(
            model_name='boot',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boots.Review'),
        ),
    ]
