# Generated by Django 3.0.8 on 2020-09-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0007_auto_20200911_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
