# Generated by Django 3.0.8 on 2020-09-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0008_remove_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
