# Generated by Django 3.0.8 on 2020-09-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0009_auto_20200911_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boot',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='boot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boots.Boot'),
        ),
    ]
